version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pcs
    networks:
      - pcs

  app:
    build: .
    depends_on:
      - db
    networks:
      - pcs

networks:
  pcs:
